### ISSUE TITLE
Every call results in error

### ISSUE THREAD

**Issue by edyu** [lhorie/rem#6]
The easiest way to reproduce it is to go to "https://rem-rest-api.herokuapp.com/api/users" on chrome.

{
  "message": "Unexpected end of JSON input",
  "stack": "SyntaxError: Unexpected end of JSON input\n    at Object.parse (native)\n    at /app/Type.js:15:44\n    at Array.forEach (native)\n    at /app/Type.js:14:25\n    at Array.map (native)\n    at Object.decode (/app/Type.js:12:17)\n    at getData (/app/index.js:126:18)\n    at Server.route (/app/index.js:31:12)\n    at emitTwo (events.js:106:13)\n    at Server.emit (events.js:191:7)"
}

**Comment by timbotron** [comment]
This appears to not be the case anymore; tested in Chrome. I vote to close this issue.
